### ISSUE TITLE
3.6.2-r0 : postInstallation error

### ISSUE THREAD

**Issue by Badisi** [bitnami/bitnami-docker-joomla#11]
Mac OSX Yosemite 10.10.5
Docker for Mac 1.12.0-a (build: 11213)

Installing the latest bitnami-joomla (3.6.2-r0) through docker-compose will result in the following error:
```
harpoon INFO  Initializing php
harpoon INFO  php successfully initialized
harpoon INFO  Initializing apache
harpoon INFO  apache successfully initialized
harpoon INFO  Initializing joomla
Error executing 'postInstallation': mysqlCore.checkConnection is not a function
exited with code 1
```

Using the previous version 3.6.0-r1 is working fine.

**Comment by chipironcin** [comment]
Hi @Badisi 
This is a known issue that happened before in
https://github.com/bitnami/bitnami-docker-drupal/issues/15

I will update the dependencies accordingly and let you know when it is fixed.
Sorry for the inconveniences

**Comment by chipironcin** [comment]
Hi again!
The issue should be now gone, I merged https://github.com/bitnami/bitnami-docker-joomla/pull/12

We didn't update the dependencies accordingly when bumped the new version.

You would probably need to pull latest bitnami/drupal to override the bugged one
`docker pull bitnami/drupal`

Please, confirm it is now working for you (in order to close the issue) and don't hesitate in reporting any other error or issue you may find while using our containers :)

**Comment by Badisi** [comment]
Hi @chipironcin 
As always, I really appreciate your quick support, thanks!

I will try updating with the latest image tonight and let you know if it works.

PS: I'll probably need to pull the latest "joomla" not "drupal" ;-)

**Comment by Badisi** [comment]
Resolved
