### ISSUE TITLE
Install without sample content

### ISSUE THREAD

**Issue by renich** [bitnami/bitnami-docker-joomla#72]
I'd love to be able to install without the sample content. Is there any way to do this? (using it on k8s through helm)

**Comment by andresbono** [comment]
Hi @renich, there is an environment variable for this purpose, `JOOMLA_LOAD_SAMPLE_DATA`. Its default value is `yes`, but you can set it to `JOOMLA_LOAD_SAMPLE_DATA=no`:

https://github.com/bitnami/bitnami-docker-joomla/blob/26cf8135e8bd019c933a5861b7d7b9667795faaa/3/debian-10/rootfs/opt/bitnami/scripts/joomla-env.sh#L67

This variable is not documented in the README of the container, so we will add it.

---

In order to provide this env-var in through the Helm Chart, you can use the [`extraEnvVars` value](https://github.com/bitnami/charts/tree/master/bitnami/joomla#joomla-parameters), see the [values.yaml](https://github.com/bitnami/charts/blob/868ef68c96a2297c2db4080f6797d45544378bce/bitnami/joomla/values.yaml#L96-L101):

```yaml
## An array to add extra env vars
## For example:
##
extraEnvVars: []
#  - name: BEARER_AUTH
#    value: true
```

Let us know if you find any issues.

**Comment by renich** [comment]
Thanks! Somehow, I missed this on the README. Sorry.

**Comment by andresbono** [comment]
No problem!
