### ISSUE TITLE
Support for Bullseye

### ISSUE THREAD

**Issue by pvklink** [bitnami/bitnami-docker-joomla#74]
### Name and Version

latest joomla

### What is the problem this feature will solve?

Like to use the image on my rpi 4b with bullseye and mysql

### What is the feature you are proposing to solve the problem?

Working on the latest OS

### What alternatives have you considered?

Another CMS thats supports bullseye

**Comment by carrodher** [comment]
There are different topics involved here, one thing is the Debian version. At this moment the Bitnami OpenSource images are based on Debian 10, but there are plans to move them to Debian 11 in the mid-term.

Another thing is the use of those images in Raspberry Pi whose architecture is ARM instead of AMD, for this topic, there are no plans to work on it in the short/mid-term.
